name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t nginx-app .

      - name: Run container
        run: docker run -d -p 8080:80 --name web nginx-app

      - name: Check running containers
        run: docker ps

      - name: Test application
        run: curl -I http://localhost:8080 || true

      - name: Stop container
        if: always()
        run: docker stop web && docker rm web
